### ISSUE TITLE
"Connecting..." message hanging on iOS app 

### ISSUE THREAD

**Issue by rveeblefetzer** [mattermost/mattermost-mobile#1106]
#### Summary
In any channel, `Connecting...` and throbber icon shows below the channel name and hangs, despite new messages loading and the ability to scroll up and load more previous messages.

#### Environment Information

- Device Name: iPhone 5
- OS Version: iOS 10.3.3
- Mattermost App Version: 1.4.0 (Build 63)
- Mattermost Server Version: 4.3.0 (Build 4.3.1)

#### Steps to reproduce
Launch the app. If it makes a difference, I'm in China, but the result is no different if I'm on Wifi with VPN, mobile data without VPN, or mobile data with a different VPN.

#### Expected behavior
I expect that if retrieving new messages, the app has indeed connected to the server and the "Connecting..." notification would go away.

#### Observed behavior
The gray bar with `Connecting...` and the spinning throbber icon doesn't disappear
![mattermost](https://user-images.githubusercontent.com/1522738/32547010-ca951d00-c4bb-11e7-8ae8-dc5766eeb76b.PNG)
 
#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by lfbrock** [comment]
Hi @rveeblefetzer, can you go to the mobile app settings menu > Report a Problem, and check if there's any errors showing up there?

**Comment by rveeblefetzer** [comment]
@lfbrock No, there is no error section under there. Also weird, I don't have that hanging notification, whether on wifi or mobile data, without VPN. For a little while, there was no notification, but now it says "No internet connection". Despite this, I do see a couple of new messages and I can pull up to load more previous messages.

![mattermost2](https://user-images.githubusercontent.com/1522738/32589538-fe13c296-c54f-11e7-91b2-815d2f743697.PNG)

**Comment by Matzgitz** [comment]
get the same error like rveeblefetzer on iOS11.2 beta and other devices with iOS11 different hardware.
Using latest app and server with MobileIron MDM and AppTunnel. No workaround until no.

**Comment by lfbrock** [comment]
Hi @Matzgitz and @rveeblefetzer - we think we know what's causing this, it looks like we're pinging google to check for connection right now which doesn't work for air gapped networks or if you're in a location that blocks access. 

Ticket is here to fix: https://mattermost.atlassian.net/browse/RN-495

**Comment by Matzgitz** [comment]
fixed with last update. thank you.

**Comment by el-moalo-loco** [comment]
Hello @lfbrock and all the others, I'm still experiencing this problem.

**Steps to reproduce**
1.) Open app. => Everything looks fine. "Connecting" message is not displayed.
2.) Swipe up to trigger fetch of new messages.
3.) "Connecting" message appears and stays forever.

**Device**
iPhone 5S, iOS 11.1.2

**Mattermost**
App Version 1.4.1 (Build 64), Server Version 4.4.0, Database: postgres

**General Info**
Germany
No matter what wifi
No matter if wifi or mobile connection

**Comment by lfbrock** [comment]
Hi @el-moalo-loco - can you check the NGINX settings on your site as a first step? 

https://docs.mattermost.com/mobile/mobile-troubleshoot.html#i-see-a-connecting-bar-that-does-not-go-away

**Comment by atkozhuharov** [comment]
I'm hitting the same issue with iOS 11.2.1 iPhone 7 and iOS 11.2 iPhone 5S (can't reproduce on Android).
Setup: mattermost + push proxy on a VM in GCP.

**Comment by mlazarov** [comment]
Adding AllowCorsFrom: "*" fixes this.
