### ISSUE TITLE
The text field is partially hidden on the iPhone X

### ISSUE THREAD

**Issue by nicolinuxfr** [mattermost/mattermost-mobile#1239]
#### Summary

On the iPhone X, the text field is partially hidden behind text suggestions.

#### Environment Information

- Device Name: iPhone X 
- OS Version: iOS 11.2 b5
- Mattermost App Version: build 67
- Mattermost Server Version: 4.4.0 (build 4.4.2)

#### Steps to reproduce
Write text in any channel on the iPhone X.

#### Expected behavior
The field text should be visible.

Here's what it looks like :

![img_0793](https://user-images.githubusercontent.com/2078386/33485324-492d79f4-d6a6-11e7-9d24-2b29da6133b6.PNG)

**Comment by enahum** [comment]
this was fixed by #1205 and will be available with the next release

**Comment by nicolinuxfr** [comment]
No, precisely. I’m using a version that includes this PR and the problem is still here.

**Comment by enahum** [comment]
@hmhealey care to take a look at this?

**Comment by enahum** [comment]
Closed via #1249

**Comment by nicolinuxfr** [comment]
Indeed, it’s fine with the latest build ! 👍
