### ISSUE TITLE
I can't build due to broken project dependency (mmjstool)

### ISSUE THREAD

**Issue by BeRo1985** [mattermost/mattermost-mobile#5847]
#### Summary

I can't build due to broken project dependency (mmjstool).

### Environment Information
  - Device Name: Macbook Air M1
  - OS Version: macOS 12.0.1
  - Mattermost App Version: #e9df1b3dbb07b29aea113ccf0456c78822563d26 master
  - Mattermost Server Version:

#### Steps to reproduce
Just do a fresh checkout/pull, do the appropriate preparations and try to run `npm run build:android` . 

#### Expected behavior
That it builds without any errors.

#### Observed behavior (that appears unintentional)
 I'm getting this error as follows:

>npm WARN tarball tarball data for mmjstool@git+ssh://git@github.com/mattermost/mattermost-utilities.git#3faa6075089a541d8c90ed85114e644c7a23fedf (sha512-84xbA6yRt+pEbYk/OmM9sbJQp7PkSAgqvn0N/QXuj1RKR+upxdAa6vTbTTBA+XweECN6xebCWncGJJiqWrtR1g==) seems to be corrupted. Trying again.

#### Possible fixes
Fix the mmjstool dependency ?

**Comment by dojoVader** [comment]
@BeRo1985 
Same here currently experiencing this issue but what i did was to do this

  "mmjstool": "github.com/mattermost/mattermost-utilities#3faa6075089a541d8c90ed85114e644c7a23fedf" and it installed

**Comment by namanhmhn** [comment]
I had same issue

>npm ERR! code EINTEGRITY
npm ERR! sha512-84xbA6yRt+pEbYk/OmM9sbJQp7PkSAgqvn0N/QXuj1RKR+upxdAa6vTbTTBA+XweECN6xebCWncGJJiqWrtR1g== integrity checksum failed when using sha512: wanted sha512-84xbA6yRt+pEbYk/OmM9sbJQp7PkSAgqvn0N/QXuj1RKR+upxdAa6vTbTTBA+XweECN6xebCWncGJJiqWrtR1g== but got sha512-xqr3JVKbdU38+uDYP6p+EENRg/fR2EP2Z9k3CKacDI7RRWXKeHuB0yRdPsgZuI7XCrp31mU1fGb9Ni5HJYoQ==. (687008 bytes)

I tried to open package-lock.js then replace 
`sha512-84xbA6yRt+pEbYk/OmM9sbJQp7PkSAgqvn0N/QXuj1RKR+upxdAa6vTbTTBA+XweECN6xebCWncGJJiqWrtR1g==` 
with 
`sha512-xqr3JVKbdU38+uDYP6p+EENRg/fR2EP2Z9k3CKacDI7RRWXKeHuB0yRdPsgZuI7XCrp31mU1fGb9Ni5HJYoQ==` 
then it worked

**Comment by nicolinuxfr** [comment]
I had the same issue and your solution worked @namanhmhn so thanks ! 👍

**Comment by PanderMusubi** [comment]
Fixing this issue will reintroduce Mattermost in the F-Droid app store. At the moment the last build was so old that it didn't work with contemporary servers, so the complete app is temporarily removed, until this issue has been resolved.

**Comment by PanderMusubi** [comment]
See also https://gitlab.com/fdroid/fdroiddata/-/issues/1987

**Comment by licaon-kter** [comment]
> Fixing this issue will reintroduce Mattermost in the F-Droid app store.

That's not really true, though :) 

There are more issues elsewhere :(

**Comment by PanderMusubi** [comment]
Do you have a list of which ones?

**Comment by licaon-kter** [comment]
@PanderMusubi subscribe to https://github.com/mattermost/mattermost-mobile/issues/566

**Comment by licaon-kter** [comment]
@BeRo1985 so this is fixed now?

**Comment by nicolinuxfr** [comment]
I can also confirm the error is still present… 😢

As @namanhmhn instructed, I edited the package-lock.json file to replace `sha512-d2p3iGoWbBpmYrZJnGOGoxfSeLTtwQKBQB+LeDA91RAc2RUCiMAA5kYGneSD0uK3L/TgEu6BuObQiCS2GoFMwA==` with `sha512-80k8ic7XSrvwlin2D5dtpNth4rl+zrabqfDhEJ0fZS3D5J9CvFGb7Sj7U2z6j9F2D9/FXhXV2uxi++HHsQWvYQ==` and it worked, but it's quite annoying.

**Comment by larkox** [comment]
Is this still happening on the latest beta (V2)?

**Comment by licaon-kter** [comment]
Didn't see it myself, ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12399/pipelines

**Comment by larkox** [comment]
Cool, then I will marked it as solved. If the issue comes back, feel free to reopen it.
