### ISSUE TITLE
Wrong profile picture showing for users (iOS)

### ISSUE THREAD

**Issue by gopi-krd** [mattermost/mattermost-mobile#7376]
#### Summary
Wrong profile picture showing for users (iOS). youtube or URL thumbnail images getting updated as users profile picture.

### Environment Information
  - Device Name: iphone 12 mini
  - OS Version: ios16
  - Mattermost App Version: 2.4.0
  - Mattermost Server Version:7.5.1

#### Steps to reproduce
1. Copy any URL which has thumbnail images (ex: youtube URL)
2. Paste it in any channel.
3. Look into the users in menu.
4. Once the message has been sent that thumbnail getting updated as random user's profile picture without their knowledge.

#### Expected behavior
Profile picture should not be affected unnecessarily.

#### Observed behavior (that appears unintentional)
Due to privacy cannot upload the images. also it doesn't affect the person who shares the link. It picks the random person and changes their profile picture.

#### Possible fixes
It seems issue with naming image URL or image caches.
Kindly check this issue
Thanks

**Comment by ParitoshBh** [comment]
I am affected by the same issue as well. Kind of nervous moment at first since the user confirmed that it wasn’t changed by her and I wasn’t sure what did until I came across this issue.

**Comment by douglaskanderson** [comment]
Had it happen here too.  It seems modifying any part of your profile and clicking save resolves.  I made these changes on my PC where the image was still fine.

**Comment by larkox** [comment]
@douglaskanderson In what version are you seeing this? In one of the latest versions we upgraded some libraries that should fix the issue.

**Comment by larkox** [comment]
@arantesxyz can you confirm the app version?

And just to verify it is exactly the same issue:
- The image is different only for the user and device with the problem. Everyone else, or checking on browser/desktop shows the correct image.
- The image is potentially loaded in the same context (the image it should show and the image is showing appear, for example, in the same channel)
- Login out and in again solves the issue

**Comment by animusastralis** [comment]
It's still happening randomly after each update of Mattermost app

**Comment by enpluo** [comment]
This just happened to me as well. My profile picture got changed to the logo for Fandom (version 2.17.0 build 525)

**Comment by rozenlicht** [comment]
We experience this issue regularly in our organisation. We use self-hosted server. Colleagues are seeing random images time-to-time as profile picture of other users.

**Comment by wiggels** [comment]
Glad to see I'm not the only one that has seen this! I have even seen a profile picture rendered as a random gif. Example:
![RPReplay_Final1714693016-1](https://github.com/user-attachments/assets/31c9a5be-864a-4291-ae43-82e1fcafa1b9)

**Comment by larkox** [comment]
@wiggels At what version did this start to happen?

**Comment by johnlane** [comment]
Is this still an issue? 

I just had this happen - again on iOS app. The image that appeared in the profile picture happened to be from an earlier post about a cybersecurity article and was enough to send the affected user into a complete panic.

I know the image was posted to my server by a user, but it did feel like an outside hack there for a while. Link to image is [here](https://www.bbc.co.uk/news/articles/c62rexy9y3no) (a BBC news article that was legitamitely referenced on a mattermost post) and this should charify why this sent the user into a complete panic.

Please, you need to fix this, it really isn't good. Especially as it's been a known issue for some time.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-68391.

**Comment by lieut-data** [comment]
@enahum, I recall your doing some work around image caches: might that have resolved this issue? I can't reproduce it presently on Community.

**Comment by enahum** [comment]
I did but long before this report.. not sure if youtube posters were included
